Upgrade to curity 3.0
curityio/signicat-authenticator pull request #10
Opened 2018-06-08 15:17 UTC by renatoathaydes

Improved internal build (where access to the Curity's repositories is possible) and better documented pom dependencies.

2018-06-11 18:49 UTC, travisspencer commented
Build fails:

> [ERROR] Failed to execute goal on project identityserver.plugins.authenticators.signicat: Could not resolve dependencies for project io.curity.identityserver.plugin:identityserver.plugins.authenticators.signicat:jar:1.0.0: The following artifacts could not be resolved: se.curity.identityserver:identityserver.sdk:jar:3.0.0, com.signicat:opensaml:jar:1.1-PATCH-6: **Could not find artifact se.curity.identityserver:identityserver.sdk:jar:3.0.0** in central (http://repo.maven.apache.org/maven2)

2018-06-12 12:11 UTC, travisspencer requested changes

2018-06-12 12:11 UTC, travisspencer commented on pom.xml
> +            <groupId>com.signicat</groupId>
this isn't needed. The OpenSAML types that are used are in that "mock" defined above `com.signicat:java-connector:4.0.1`

2018-06-13 14:06 UTC, renatoathaydes commented on internal-pom.xml
> +    <name>Signicat Authenticator</name>
This internal POM allows us to build this project without downloading jars manually, as the Signicat jars are installed in the internal Maven repos.
With `mvn package` all the jars we need to install will be placed into `target/libs`.

2018-06-13 14:07 UTC, renatoathaydes commented on pom.xml
> +            <artifactId>kotlin-test</artifactId>
but how did this get here!?!?!? IntelliJ magic.

2018-07-04 09:28 UTC, travisspencer requested changes

2018-07-04 09:28 UTC, travisspencer commented on README.rst
> +For this to succeed, however, the `Signicat Connector for Java <https://support.signicat.com/display/S2/Signicat+Connector+for+Java>`_ needs to be installed into a Maven repository which is accessibl
link not fixed

2018-07-06 06:41 UTC, renatoathaydes commented on README.rst
> +For this to succeed, however, the `Signicat Connector for Java <https://support.signicat.com/display/S2/Signicat+Connector+for+Java>`_ needs to be installed into a Maven repository which is accessibl
Fixed now.

2018-07-07 07:48 UTC, travisspencer approved these changes

2018-07-07 07:49 UTC, merged